on: [workflow_dispatch]

name: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: macos-latest
          TARGET: aarch64-apple-darwin

        - os: macos-latest
          TARGET: x86_64-apple-darwin

        - os: ubuntu-latest
          TARGET: x86_64-unknown-linux-gnu

        - os: windows-latest
          TARGET: aarch64-pc-windows-msvc
          EXTENSION: .exe

        - os: windows-latest
          TARGET: x86_64-pc-windows-msvc
          EXTENSION: .exe

    steps:
    - name: Building ${{ matrix.TARGET }}
      run: echo "${{ matrix.TARGET }}"

    - name: Cache Cargo
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "v0-rust"
        env-vars: "CARGO CC CFLAGS CXX CMAKE RUST"
        workspaces: ". -> target"
        cache-targets: "true"
        cache-on-failure: "false"
        cache-all-crates: "false"
        save-if: "true"
        cache-provider: "github"

    - uses: actions/checkout@master
    - name: Install build dependencies - Rustup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable --profile default --target ${{ matrix.TARGET }} -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    # For linux, it's necessary to use cross from the git repository to avoid glibc problems
    # Ref: https://github.com/cross-rs/cross/issues/1510
    - name: Install cross for linux
      if: contains(matrix.TARGET, 'linux')
      run: |
        cargo install cross --git https://github.com/cross-rs/cross --rev 1b8cf50d20180c1a394099e608141480f934b7f7

    - name: Install cross for mac and windows
      if: ${{ !contains(matrix.TARGET, 'linux') }}
      run: |
        cargo install cross

    - name: Install libraries
      if: contains(matrix.TARGET, 'linux')
      run: sudo apt-get install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev

    - name: Build
      run: |
        cross build --verbose --release --target=${{ matrix.TARGET }}

    - name: Rename
      run: cp target/${{ matrix.TARGET }}/release/open_lights_manager{{ matrix.EXTENSION }} open_lights_manager-${{ matrix.TARGET }}${{ matrix.EXTENSION }}

    - uses: actions/upload-artifact@master
      with:
        name: open_lights_manager-${{ matrix.TARGET }}${{ matrix.EXTENSION }}
        path: open_lights_manager-${{ matrix.TARGET }}${{ matrix.EXTENSION }}

  upload_release:
    permissions:
      contents: write
    needs: build
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Get Version'
        uses: SebRollen/toml-action@v1.2.0
        id: read_toml
        with:
          file: 'Cargo.toml'
          field: 'package.version'

      - name: Retrieve Artifacts
        uses: actions/download-artifact@v4
        with:
          path: libs/
          merge-multiple: true

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          tag_name: ${{ steps.read_toml.outputs.value }}
          prerelease: false
          name: Open Lights Manager ${{ steps.read_toml.outputs.value }}
          files: libs/*
          generate_release_notes: true
          overwrite: true
